name: Build 

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install 
        run: dotnet restore WebApi

      - name: Build 
        run: dotnet build WebApi --configuration Release --no-restore

      #- name: Test 
      #  run: dotnet test WebApi --configuration Release --no-build
